ShoeApp/urls.py
from django.contrib import admin
from django.urls import path
from shoe import views
from django.conf import settings
from django.conf.urls.static import static


# make up of a url is the name of the route  , package with templates and then method in templates function.
urlpatterns = [
                  path('admin/', admin.site.urls),
                  path('', views.show),
                  path('shoe', views.shoe),
                  path('show', views.show),
                  path('edit/<int:id>', views.edit),
                  path('update/<int:id>', views.update),
                  path('delete/<int:id>', views.destroy),
                  path('checkout/<int:id>', views.checkout),
                  path('checkoutpay/<int:id>', views.checkoutpay)
              ] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

shoe/models.py
from django.db import models


# Create your models here.
class Shoe(models.Model):
    shoe_name = models.CharField(max_length=100)
    shoe_image = models.ImageField(null=True, blank=True, upload_to="images/")
    shoe_price = models.CharField(max_length=100)
    shoe_description = models.CharField(max_length=15)

    class Meta:
        db_table = "shoe"


class Checkout(models.Model):
    transactionid = models.CharField(db_column='transactionid', max_length=100, blank=False)
    amount = models.CharField(db_column='amount', max_length=100, blank=False)
    phone = models.CharField(db_column='phone', max_length=100, blank=False)

    class Meta:
        db_table = 'checkout'
        verbose_name = 'checkout'
        verbose_name_plural = 'checkouts'

    def __unicode__(self):
        return self.transactionid

    def __str__(self):
        return self.transactionid

shoe/forms.py
from django import forms
from shoe.models import Shoe


class ShoeForm(forms.ModelForm):
    class Meta:
        model = Shoe
        fields = "__all__"

shoe/views.py
from django.shortcuts import render, redirect
from shoe.forms import ShoeForm
from shoe.models import Shoe, Checkout

from django.shortcuts import render, redirect
from shoe.models import Checkout
from shoe.models import Shoe
from django.http import HttpResponse
from django_daraja.mpesa.core import MpesaClient


# Create your templates here.


# Create your views here.


# .save() is the ORM equivalent of the SQL insert to statement.
def show(request):
    shoes = Shoe.objects.all()
    return render(request, "show.html", {'shoes': shoes})


def shoe(request):
    if request.method == "POST":
        form = ShoeForm(request.POST, request.FILES)
        if form.is_valid():
            try:
                form.save()
                return redirect('/show')
            except:
                pass
    else:
        form = ShoeForm()
    return render(request, 'index.html', {'form': form})


# .all() is the ORM equivalent of the SQL statement "SELECT * FROM tablename"


# .get is the ORM equivalent of the SQL statement "SELECT * FROM tablename WHERE id = ? "
# method update carries the update process for a single record

def edit(request, id):
    shoe = Shoe.objects.get(id=id)
    return render(request, 'edit.html', {'shoe': shoe})


def update(request, id):
    shoe = Shoe.objects.get(id=id)
    form = ShoeForm(request.POST, instance=shoe)
    if form.is_valid():
        form.save()
        return redirect("/show")
    return render(request, 'edit.html', {'shoe': shoe})


# .delete() is the ORM equivalent of the statement SQL : " DELETE FROM tablename WHERE id = ? "
def destroy(request, id):
    shoe = Shoe.objects.get(id=id)
    shoe.delete()
    return redirect("/show")


def checkout(request, id):
    shoes = Shoe.objects.get(id=id)
    return render(request, "checkout.html", {'shoes': shoes})


def checkoutpay(request, id):
    shoes = Shoe.objects.get(id=id)
    if request.method == "POST":

        # capture input
        amount = shoes.shoe_price
        phoneNumber = request.POST.get('contact')

        # validation on the entries
        if not phoneNumber or not phoneNumber.isdigit():
            return HttpResponse("invalid phone number")
        if not amount or not amount.isdigit():
            return HttpResponse("invalid phone number")
        # Mpesa processes
        cl = MpesaClient()
        phone_number = int(phoneNumber)
        amount = int(amount)
        account_reference = 'CELESTIN ENTERPRISES'
        transaction_desc = 'Evanicela Payment'
        callback_url = 'https://api.darajambili.com/express-payment'
        response = cl.stk_push(str(phone_number), amount, account_reference, transaction_desc, callback_url)
        return HttpResponse(response)
    else:
        return render(request, "checkout.html", {'shoes': shoes})

shoe/templates/checkout.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Shoe Gallery</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-GLhlTQ8iRABdZLl6O3oVMWSktQOp6b7In1Zl3/Jr59b6EGGoI1aFkw7cmDA6j6gD" crossorigin="anonymous">
</head>
<body>
<div class="container">
    <form method="POST" class="form-control" action="/checkoutpay/{{ shoes.id }}">
    {% csrf_token %}
    <div class="form-group">
       <p>Shoe Name: {{ shoes.shoename }}</p>
    </div>
        <div class="form-group">
       <p>Shoe Description: {{ shoes.description }}</p>
    </div>
        <div class="form-group">
       <p>Shoe Price: {{ shoes.price }}</p>
    </div>
     <div class="form-group">
        <input class="form-control" type="text"  name="contact" id="contact" required maxlength="15" placeholder="Enter Mpesa Phone Number" />
    </div>
        <br>
      <div class="form-group">
    <button type="submit" class="btn btn-primary">Proceed to Checkout</button>
    </div>

</form>

</div>

<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/js/bootstrap.bundle.min.js" integrity="sha384-w76AqPfDkMBDXo30jS1Sgez6pr3x5MlQ1ZAGC+nuZB+EYdgRZgiwxhTBTkF7CXvN" crossorigin="anonymous"></script>
</body>
</html>

shoe/templates/edit.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Index</title>
    {% load static %}

    <link rel="stylesheet" href="{% static 'css/style.css' %}"/>
    {% load bootstrap5 %}
    {% bootstrap_css %}
    {% bootstrap_javascript %}
</head>
<body>
<form method="POST"    action="/update/{{shoe.id}}">
    {% csrf_token %}
    <div class="container" >
        <br>
        <div class="form-group  row"  >
            <label class="col-sm-2 col-form-label "></label>
            <div class="col-sm-4  bg-primary">
                <h2>Update shoes</h2>
            </div>
             <br>
            <br>
            <div >
                <div class="form-group row">
                    <label class="col-sm-2 col-form-label">Shoe Name:</label>
                    <div class="col-sm-4">
                        <input type="text" name="shoe_name" id="id_shoe_name" required maxlength="100" value="{{ shoe.shoe_name }}" />
                    </div>
                </div>
                <div class="form-group row">
                    <label class="col-sm-2 col-form-label">Shoe Image:</label>
                    <div class="col-sm-4">
                        <input type="text" name="shoe_image" id="id_shoe_image" required maxlength="254" value="{{ shoe.shoe_image }}" />
                    </div>
                </div>

                <div class="form-group row">
                    <label class="col-sm-2 col-form-label">Shoe Price:</label>
                    <div class="col-sm-4">
                        <input type="text" name="shoe_price" id="id_shoe_price" required maxlength="254" value="{{ shoe.shoe_price }}" />
                    </div>
                </div>
                <div class="form-group row">
                    <label class="col-sm-2 col-form-label">Shoe description:</label>
                    <div class="col-sm-4">
                        <input type="text" name="shoe_description" id="id_shoe_description" required maxlength="15" value="{{ shoe.shoe_description }}" />
                    </div>
                </div>
            </div>
        </div>
        <div class="form-group row">
            <label class="col-sm-2 col-form-label"></label>
            <div class="col-sm-4">
                <br>
                <button type="submit" class="btn btn-danger">Update</button>
            </div>
        </div>
    </div>
</form>
</body>
</html>

shoe/templates/index.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
     <meta name="viewport" content="width=device-width, initial-scale=1">
  <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/css/bootstrap.min.css" rel="stylesheet">
  <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/js/bootstrap.bundle.min.js"></script>
    <title>Index</title>

    {#    allows us to load static files #}
    {% load static %}
    <link rel="stylesheet" href="{% static 'css/style.css' %}"/>
    {% load bootstrap5 %}
  {% bootstrap_css %}
  {% bootstrap_javascript %}
</head>
<body>
<form method="POST"  class="tinymask" action="/shoe" enctype="multipart/form-data">
    {% csrf_token %}
    <div class="container">
        <br>
        <div class="form-group bg-primary row">
            <label class="col-sm-2 col-form-label"></label>
            <div class="col-sm-4">
                <h3>Enter information of the shoe</h3>
            </div>
        </div>
         <br>
        <div class="form-group  row">
            <label class="col-sm-2 col-form-label">Shoe Name:</label>
            <div class="col-sm-4">
                {{ form.shoe_name }}
            </div>
        </div>
        <div class="form-group row">
            <label class="col-sm-2 col-form-label">Shoe Image:</label>
            <div class="col-sm-4">
                {{ form.shoe_image }}
            </div>
        </div>
        <div class="form-group row">
            <label class="col-sm-2 col-form-label">Shoe Price:</label>
            <div class="col-sm-4">
                {{ form.shoe_price }}
            </div>
        </div>
        <div class="form-group row">
            <label class="col-sm-2 col-form-label">Shoe description:</label>
            {#        this section maps the value given by user to the model field i.e employee.models #}
            <div class="col-sm-4">
                {{ form.shoe_description}}
            </div>
        </div>
        <div class="form-group row">
            <label class="col-sm-2 col-form-label"></label>
            <div class="col-sm-4">
                <button type="submit" class="btn btn-danger">Submit</button>
            </div>
        </div>
    </div>
</form>
</body>
</html>

shoe/templates/show.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Shoes Records</title>
    {% load static %}
    <link rel="stylesheet" href="{% static 'css/style.css' %}"/>
    {% load bootstrap5 %}
    {% bootstrap_css %}
    {% bootstrap_javascript %}

</head>
<body>
<table class="table table-striped table-bordered table-sm">
    <thead class="bg-primary">
    <tr>
        <th>Shoe ID</th>
        <th>Shoe Name</th>
        <th>Shoe Image</th>
        <th>Shoe Price</th>
        <th>Shoe Description</th>
        <th>Actions</th>
    </tr>
    </thead>
    <tbody>

    {% for shoe in shoes %}
        <tr>
            <td>{{ shoe.id }}</td>
            <td>{{ shoe.shoe_name }}</td>
            <td> <img src="{{ shoe.shoe_image }}" width="300"></td>
            <td>{{ shoe.shoe_price }}</td>
            <td>{{ shoe.shoe_description }}</td>
            <td>
                <a href="/edit/{{ shoe.id }}"><span class="btn btn-danger" >Edit</span></a>
               <a href="/delete/{{ shoe.id }}"><span class="btn btn-danger" >delete</span></a>
                <a href="/checkout/{{ shoe.id }}" class="btn btn-success"> Checkout </a>
            </td>
        </tr>
        <br>
    {% endfor %}
    </tbody>
</table>
<br>
<br>
<center><a href="/shoe" class="btn btn-primary">Add New Shoe</a></center>
</body>
</html>